#define COMSIG_GLOB_INTEL_DISK_PRINTED "!intel_disk_printed"
#define COMSIG_GLOB_INTEL_COMPUTER_ACTIVATED "!intel_computer_activated"
#define COMSIG_DISK_EXPIRY "intel_disk_expiring"
#define COMSIG_DAYLIGHT_NEW_DAY "daylight_new_day"
#define COMSIG_DAYLIGHT_DAY_START "daylight_day_start"
#define COMSIG_DAYLIGHT_NIGHT_START "daylight_night_start"
#define COMSIG_DAYLIGHT_UPDATED "daylight_updated"
